# Uncomment the next line to define a global platform for your project
# platform :ios, '10.2'
use_frameworks!

target 'PokeDex3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 4.0'
 
end
